domain: meet.hrnbyl.com
certificateArn: "arn:aws:acm:ap-south-1:100390193083:certificate/93f98744-29a4-407b-87eb-0fad95085f39"

networking:
  jvbUdpPort: 10000

images:
  web: jitsi/web:stable
  prosody: jitsi/prosody:stable
  jicofo: jitsi/jicofo:stable
  jvb: jitsi/jvb:stable

jitsiSecrets:
  jicofoComponentSecret: "JicofoSecret123!"
  jicofoAuthPassword: "JicofoAuthPassword123!"
  jvbAuthPassword: "JvbAuthPassword123!"

xmpp:
  authDomain: "auth.meet.hrnbyl.com"
  mucDomain: "muc.meet.hrnbyl.com"
  internalMucDomain: "internal-muc.meet.hrnbyl.com"

metrics:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
