apiVersion: v1
kind: Service
metadata:
  name: jitsi-prosody
  namespace: jitsi
spec:
  type: ClusterIP
  selector:
    app: jitsi-prosody
  ports:
    - name: xmpp-client
      port: 5222
      targetPort: 5222
    - name: xmpp-component
      port: 5347
      targetPort: 5347
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi-prosody
  namespace: jitsi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jitsi-prosody
  template:
    metadata:
      labels:
        app: jitsi-prosody
    spec:
      containers:
        - name: prosody
          image: {{ .Values.images.prosody }}
          ports:
            - containerPort: 5222
            - containerPort: 5347
          env:
            - name: XMPP_DOMAIN
              value: {{ .Values.domain }}