apiVersion: v1
kind: Service
metadata:
  name: jitsi-prosody
  namespace: jitsi
spec:
  type: ClusterIP
  selector:
    app: jitsi-prosody
  ports:
    - name: xmpp-client
      port: 5222
      targetPort: 5222
    - name: xmpp-component
      port: 5347
      targetPort: 5347
    - name: http
      port: 5280
      targetPort: 5280
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi-prosody
  namespace: jitsi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jitsi-prosody
  template:
    metadata:
      labels:
        app: jitsi-prosody
    spec:
      containers:
        - name: prosody
          image: {{ .Values.images.prosody }}
          ports:
            - containerPort: 5222
            - containerPort: 5347
            - containerPort: 5280
          env:
            - name: XMPP_DOMAIN
              value: {{ .Values.domain }}
            - name: XMPP_AUTH_DOMAIN
              value: {{ .Values.xmpp.authDomain }}
            - name: XMPP_MUC_DOMAIN
              value: {{ .Values.xmpp.mucDomain }}
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: {{ .Values.xmpp.internalMucDomain }}
            - name: JICOFO_COMPONENT_SECRET
              value: {{ .Values.jitsiSecrets.jicofoComponentSecret }}
            - name: JICOFO_AUTH_PASSWORD
              value: {{ .Values.jitsiSecrets.jicofoAuthPassword }}
            - name: JVB_AUTH_PASSWORD
              value: {{ .Values.jitsiSecrets.jvbAuthPassword }}
            - name: PUBLIC_URL
              value: "https://{{ .Values.domain }}"
            - name: ENABLE_XMPP_WEBSOCKET
              value: "1"